### ISSUE TITLE
Question about Peepeth becoming free

### ISSUE THREAD

**Issue by RommelTJ** [matter-labs-archive/PeepethClient#24]
**I'm submitting a ...**

- [x] other (Please do not submit support requests here (below))

Hi. Bevan (Peepeth founder) recently announced that [using Peepeth is now free](https://peepeth.com/a/free). How does that announcement change this client? I've been confused at how to tackle some of the outstanding issues here because I don't know how to fund my account without using real money and it looks like I'm not the only one so it would be nice to get some clarification on this. For example, how is the account sign up process changing in PeepethClient?

**Comment by BaldyAsh** [comment]
@RommelTJ hi! Will discuss it with Bevan as soon as possible
